[build]
  publish = "."
  command = "./build.sh"

[build.environment]
  ENABLE_LIMITED_VIEW = "true"
  START_DATE_OVERRIDE = "2025-09-30"
  DAYS_TO_SHOW = "20"
  ENABLE_COMING_SOON = "true"
  # No TEST_DATE_OVERRIDE = uses actual current date for real-time progressive reveal

# Redirect rules (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200