[build]
  publish = "."
  command = "./build.sh"

[build.environment]
  ENABLE_LIMITED_VIEW = "true"
  START_DATE_OVERRIDE = "2025-09-29"
  DAYS_TO_SHOW = "3"

# Redirect rules (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200